### ISSUE TITLE
Travellers cant be associated with Insurance.

### ISSUE THREAD

**Issue by Peterf89** [michielvanveldhuizen/percur#1]
Because the RequestTraveller is just a name typed by a person there's no guarantee that it will exist in the active directory, and thats the only way to get the InsureeGUID.

**Comment by michielvanveldhuizen** [comment]
je bent zelf een issue :D :100:  punten

**Comment by michielvanveldhuizen** [comment]
:banana:

**Comment by Peterf89** [comment]
Doe tenminste eens alsof je nog een beetje leeft @michielvanveldhuizen :finnadie:

**Comment by Peterf89** [comment]
Doe tenminste eens alsof je nog een beetje leeft @michielvanveldhuizen :finnadie:

**Comment by Peterf89** [comment]
Doe tenminste eens alsof je nog een beetje leeft @michielvanveldhuizen :finnadie:

**Comment by Peterf89** [comment]
Doe tenminste eens alsof je nog een beetje leeft @michielvanveldhuizen :finnadie:

**Comment by Peterf89** [comment]
Doe tenminste eens alsof je nog een beetje leeft @michielvanveldhuizen :finnadie:

**Comment by Peterf89** [comment]
Doe tenminste eens alsof je nog een beetje leeft @michielvanveldhuizen :finnadie:
