### ISSUE TITLE
Cant create travelrequest with rentalcar

### ISSUE THREAD

**Issue by Peterf89** [michielvanveldhuizen/percur#3]
Because: {"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_dbo.RentalCarRequest_dbo.RequestTraveller_DriverID\". The conflict occurred in database \"PercurrentisDB\", table \"dbo.RequestTraveller\", column 'Id'.\r\nThe statement has been terminated."}

**Comment by michielvanveldhuizen** [comment]
...
if (!options.hasRentalCar) {
                    _.forEach(request.RentalCarRequests, function (val) {
                        removeRentalcar(request, val);
                    });
                } else {
                    _.forEach(request.RentalCarRequests, function (val) {
                        //Setting the first traveller as driver if there are no drivers set
                        if (val.DriverID == 0) {
                            val.DriverID = request.TravelRequest_RequestTravellers[0].RequestTraveller.Id;
                        }
                    });
                }...
